### ISSUE TITLE
500 internal server error on startup

### ISSUE THREAD

**Issue by korneliuscode** [pgerke/homebridge-freeathome-local-api#33]
hi, I installed and configured the plugin and tried with 2 different users. The result is the same. I get this error when booting homebridge. Any ideas?

My sysAP is on 3.1.0 Rev 9754.

```
[27/11/2022, 22:35:59] [My free@home Setup] Received HTTP 500 status code unexpectedly: <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
</body>
</html>

[27/11/2022, 22:36:00] [My free@home Setup] Device discovery failed Error: Received HTTP 500 status code unexpectedly: <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
</body>
</html>

    at s.<anonymous> (/var/lib/homebridge/node_modules/homebridge-freeathome-local-api/node_modules/freeathome-local-api-client/dist/cjs/webpack:/freeathome-local-api-client/src/system-access-point.ts:388:15)
    at Generator.next (<anonymous>)
    at u (/var/lib/homebridge/node_modules/homebridge-freeathome-local-api/node_modules/freeathome-local-api-client/dist/cjs/index.js:1:161693)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by pgerke** [comment]
Hi, the error message you sent indicates your SysAP responded with a HTTP 500 error to a request the plugin is sending to retrieve the device configuration. Can you confirm you have a second generation System Access Point and local API is enabled? The firmware version is fine, I'm running the same one.

**Comment by korneliuscode** [comment]
Actually the local api was the issue. Fixed it by enabling it and using the username given for the API. Thanks for the hint!!

**Comment by pgerke** [comment]
Perfect, I'm happy to hear your issue is resolved!
